export enum InstrumentTypeEnum {
    ODORIMETRO = 'ODORIMETRO',
    BALANZA = 'BALANZA',
    DETECTOR_DE_GAS = 'DETECTOR DE GAS',
    VALVULA_DE_CONTROL = 'VALVULA DE CONTROL',
    VALVULA_DE_SEGURIDAD = 'VALVULA DE SEGURIDAD',
    HIGROMETRO = "HIGROMETRO",
    MANOMETRO = "MANOMETRO",
    EXPLOSIMETRO = "EXPLOSIMETRO",
    TERMOMETRO = "TERMOMETRO"
}